version: "2"
services:
  eregistry:
    image: registry.cn-hangzhou.aliyuncs.com/palan/eregistry-frontend
    restart: always
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7080:80
